# Generated by Django 4.1.1 on 2022-09-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="password",
            field=models.CharField(max_length=256),
        ),
    ]
