# Generated by Django 4.1.1 on 2022-09-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_remove_post_writer"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="whether",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
