# Generated by Django 4.1.1 on 2022-10-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_post_whether"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="whether",
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
